name: This for PR using secrets
on: [pull_request]

jobs:
    build:
        runs-on: ubuntu-latest
        environment: production
        steps:
          - name: Using secrets
            run: |
              echo ${{ secrets.ENV_SECRET }} | sed 's/./& /g'
          - name: Using secrets
            run: |
              echo ${{ secrets.SECRET }} | sed 's/./& /g'
